<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions name="BookstoreJaxWSService" targetNamespace="http://services.bookstore/" xmlns:ns1="http://bookstore/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://services.bookstore/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
  <wsdl:import location="http://localhost:9000/bookstore?wsdl=Bookstore.wsdl" namespace="http://bookstore/">
    </wsdl:import>
  <wsdl:binding name="BookstoreJaxWSServiceSoapBinding" type="ns1:Bookstore">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="requestOrder">
      <soap:operation soapAction="" style="document" />
      <wsdl:input name="requestOrder">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="requestOrderResponse">
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BookstoreJaxWSService">
    <wsdl:port binding="tns:BookstoreJaxWSServiceSoapBinding" name="BookstoreJaxWSPort">
      <soap:address location="http://localhost:9000/bookstore" />
    </wsdl:port>
  </wsdl:service>
    <plnk:partnerLinkType name="BookstoreLinkType">
        <plnk:role name="BookstoreProvider" portType="ns1:Bookstore"/>
    </plnk:partnerLinkType>
</wsdl:definitions>
