<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions name="SupplierFacade" targetNamespace="http://infosys.tuwien.ac.at/aic10/ass1/dto/supplier" xmlns:ns1="http://bookstore/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://infosys.tuwien.ac.at/aic10/ass1/dto/supplier" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
  <wsdl:import location="http://localhost:9000/supplierfacade?wsdl=Supplier.wsdl" namespace="http://bookstore/">
    </wsdl:import>
  <wsdl:binding name="SupplierFacadeSoapBinding" type="ns1:Supplier">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="supplierOrder">
      <soap:operation soapAction="" style="document" />
      <wsdl:input name="supplierOrder">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="supplierOrderResponse">
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SupplierFacade">
    <wsdl:port binding="tns:SupplierFacadeSoapBinding" name="SupplierPT">
      <soap:address location="http://localhost:9000/supplierfacade" />
    </wsdl:port>
  </wsdl:service>
    <plnk:partnerLinkType name="SupplierLinkType">
        <plnk:role name="SupplierProvider" portType="ns1:Supplier"/>
    </plnk:partnerLinkType>
</wsdl:definitions>
